version: '2'

services:
  users-app:
    image: 'users:latest'
    container_name: users-app
    depends_on:
      users-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users-db:5432/users-db
      - SPRING_DATASOURCE_USERNAME=users-db-user
      - SPRING_DATASOURCE_PASSWORD=users-db-password
    ports:
      - 8081:8080
  users-db:
    image: 'postgres:16-alpine'
    container_name: users-db
    environment:
      - POSTGRES_DB=users-db
      - POSTGRES_USER=users-db-user
      - POSTGRES_PASSWORD=users-db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d users-db -U users-db-user"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
