name: Docker (Test)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull Image
      run: docker pull sboe0705/users:latest && docker images
    - name: Tag Image
      run: docker tag sboe0705/users:latest ghcr.io/${{ github.repository_owner }}/users:latest && docker images
    - name: Log into Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Push Image
      run: docker push ghcr.io/${{ github.repository_owner }}/users:latest

